import React, { useState } from "react";

interface FixItem {
  id: string;
  severity: string;
  pts: string;
  title: string;
  why: string;
  whereTo?: string;
  whereToWarn?: string;
  language: string;
  filename: string;
  code: string;
}

interface PlanCardProps {
  domain: string;
  score: { total: number; band: string };
  fixes: FixItem[];
  planDownloadUrl?: string | null;
}

export const PlanCard: React.FC<PlanCardProps> = ({
  domain,
  score,
  fixes,
  planDownloadUrl,
}) => {
  const [isDownloading, setIsDownloading] = useState(false);

  const handleDownload = () => {
    setIsDownloading(true);
    try {
      if (planDownloadUrl) {
        window.open(planDownloadUrl, "_blank");
      } else {
        // Fallback client-side markdown generator
        const planMd = `# AEO Remediation Plan for ${domain}

> Generated by AEO Ready (https://aeoready.co)
> Date: ${new Date().toUTCString()}
> Overall Score: ${score.total}/100 (GRADE ${score.band})

---

## Action Plan — Code Remedies for Claude Code & Cursor

${fixes
  .map(
    (f, idx) => `### Step ${idx + 1}: ${f.title} (${f.pts})
**Severity**: ${f.severity}
**Reason**: ${f.why}
${f.whereTo ? `**Location**: ${f.whereTo}\n` : ""}
\`\`\`${f.language}
${f.code}
\`\`\`
`
  )
  .join("\n\n")}

---
*End of remediation plan. Save this file to your project root to apply with AI coding assistants.*`;

        const blob = new Blob([planMd], { type: "text/markdown;charset=utf-8" });
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = url;
        link.download = `${domain}-aeo-fix-plan.md`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
      }
    } finally {
      setTimeout(() => setIsDownloading(false), 500);
    }
  };

  return (
    <div className="card plan-card">
      <div className="plan-copy">
        <p className="label mt-0">Automated Remediation</p>
        <h3 className="plan-title">Download step-by-step recommendations</h3>
        <p className="plan-sub">
          One Markdown file with every step-by-step recommendation below — the evidence, the code, and the instructions.
          Drop it into Claude Code, Cursor, or ChatGPT to implement the recommendations instantly.
        </p>
      </div>
      <button
        id="dl-plan-btn"
        className="plan-btn"
        onClick={handleDownload}
        disabled={isDownloading}
      >
        <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2.5">
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3" />
        </svg>
        {isDownloading ? "Downloading..." : "Download Recommendations (.md)"}
      </button>
    </div>
  );
};
